In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
x=data.iloc[:,3:-1]
y=data.iloc[:,-1].values

In [ ]:
x.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [ ]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [ ]:
print(x['Geography'].value_counts())
print(x['Gender'].value_counts())
print(x['NumOfProducts'].value_counts())
print(x['HasCrCard'].value_counts())
print(x['IsActiveMember'].value_counts())

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64
Male      5457
Female    4543
Name: Gender, dtype: int64
1    5084
2    4590
3     266
4      60
Name: NumOfProducts, dtype: int64
1    7055
0    2945
Name: HasCrCard, dtype: int64
1    5151
0    4849
Name: IsActiveMember, dtype: int64


In [ ]:
x.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary  
count  10000.00000    10000.000000     10000.000000  
mean       0.70550        0.515100    100090.239881  
std        0.45584        0.499797     57510.492818  
min        0.00000        0.000000        11.580000  
25%        0.00000        0.000000     51002.110000  
50%        1.00000        1.000000    100193.915000  
75%        1.00000        1.000000    149388.247500  
max        1.00000        1.000000    199992.480000

In [ ]:
x.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [ ]:
x.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

In [ ]:
#manupulation of data

In [ ]:
x=pd.get_dummies(x,drop_first=True)

In [ ]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0               1        101348.88                  0                0   
1               1        112542.58                  0                1   
2               0        113931.57                  0                0   
3               0         93826.63                  0                0   
4               1         79084.10                  0                1   

   Gender_Male  
0            0  
1            0  
2            0  
3            0  
4            0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,stratify=y,random_state=0)

In [ ]:
print(x_train)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9414          544   53       9       0.00              1          1   
3363          747   38       2  129728.60              1          1   
2979          642   40       1  154863.15              1          1   
578           593   41       6       0.00              1          1   
7984          464   46       6  161798.53              1          1   
...           ...  ...     ...        ...            ...        ...   
8522          644   18       8       0.00              2          1   
4674          850   41       1  176958.46              2          0   
2580          697   38       6  132591.36              1          1   
872           722   35       2  163943.89              2          1   
8389          743   25       6       0.00              2          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
9414               0        125692.07                  0              

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
print(x_train)

[[-1.09958704  1.35512772  1.39224842 ... -0.57673443  1.74570632
  -1.09429439]
 [ 1.00236569 -0.08426526 -1.03327148 ...  1.7339003  -0.57283404
   0.91383087]
 [-0.08485124  0.1076538  -1.37977432 ... -0.57673443 -0.57283404
   0.91383087]
 ...
 [ 0.48464334 -0.08426526  0.35273989 ...  1.7339003  -0.57283404
  -1.09429439]
 [ 0.74350452 -0.37214386 -1.03327148 ... -0.57673443 -0.57283404
  -1.09429439]
 [ 0.9609479  -1.33173919  0.35273989 ... -0.57673443  1.74570632
   0.91383087]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_predicted=rf.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_predicted)
print(cm)

[[1919   72]
 [ 275  234]]


In [ ]:
print(accuracy_score(y_test,y_predicted))

0.8612


In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
models = []
models.append(('LogisticRegression', LogisticRegression()))
models.append(('Naive Bayes',GaussianNB()))
models.append(('RandomForest', RandomForestClassifier()))
models.append(('Decision Tree', DecisionTreeClassifier()))
models.append(('KNN', KNeighborsClassifier(n_neighbors = 5)))

In [ ]:
for name, model in models:
    print(name)
    model.fit(x_train, y_train)
    
    # Make predictions.
    predictions = model.predict(x_test)

    # Compute the error.
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(predictions, y_test))

    from sklearn.metrics import accuracy_score
    print(accuracy_score(predictions,y_test))
    print('\n')

LogisticRegression
[[1914  401]
 [  77  108]]
0.8088


Naive Bayes
[[1888  336]
 [ 103  173]]
0.8244


RandomForest
[[1918  284]
 [  73  225]]
0.8572


Decision Tree
[[1728  249]
 [ 263  260]]
0.7952


KNN
[[1873  320]
 [ 118  189]]
0.8248


